// ingredientes.js

const ingredientes = [
  "Ácido Cítrico",
  "Açúcar Refinado",
  "Açúcar Sc.",
  "Ajinomoto",
  "Alho Natural",
  "Amido de milho",
  "Aroma de Baunilha",
  "Aroma de Cebola",
  "Aroma de Chocolate",
  "Aroma de Leite Condensado",
  "Aroma de Coco",
  "Aroma de Três Leite",
  "Aroma de Maisena",
  "Aroma de Manteiga",
  "Aroma de Maria",
  "Aroma de Milho",
  "Aroma Alho",
  "Caramelo",
  "Aroma de Queijo Parmesão",
  "Bicarbonato de Amônio",
  "Bicarbonato de Sódio",
  "Cacau em pó",
  "Cebola Natural Roxa",
  "Caixa de Papelão",
  "Emb. Saco Fd. 50x80",
  "Chocolate em Pó",
  "Embalagem Transp. Lisa",
  "Embalagem folhada Cebola",
  "Embalagem folhada Alho",
  "Embalagem Folhada Manteiga",
  "Milho Inatura",
  "Farelo",
  "Fubá de milho",
  "Embalagem Milho",
  "Ezimas",
  "Embalagem 8 Grãos",
  "Embalagem Água e Sal",
  "Embalagem Integral",
  "Emb. Rainha Maisena",
  "Emb. Rainha Leite",
  "Emb. Rainha Cracker",
  "Emb. Rainha Rosca Leite",
  "Emb. Rainha Rosca Chocolate",
  "Emb. Rainha Rosca Coco",
  "Emb. Rainha Manteiga",
  "Emb. Rainha Alho",
  "Emb. Rainha Cebola",
  "Farinha de Trigo Fama Panificação",
  "Farinha de Trigo Panete Comum",
  "Farinha de Trigo Evita 2",
  "Fécula de Mandioca",
  "Fermento Instantâneo",
  "Gordura Agropalma",
  "Lecetina de Soja",
  "Manteiga Itacolomir",
  "Margarina Folhada Rica",
  "Margarina puro sabor",
  "Margarina",
  "Mel Caseiro",
  "Metabisulfito",
  "Óleo de Soja",
  "Milho Gelatinizado",
  "Gordura Líquida Vegetal",
  "Paulialfa",
  "Paulitase",
  "Paulivita",
  "Pirofosfato",
  "Sal Micronizado",
  "Sal Refinado",
  "Soro de Leite",
  "Unimelo",
  "Etiquetas Conchita",
  "Embalagem de Caixa p/ Folhada",
  "Óleo Pronto Cebola",
  "Filme Rezinite",
  "Fita Sela Caixa",
  "Gelatina de Milho",
  "Embalagem Flocão",
  "Embalagem Dallato Leite",
  "Embalagem Dallato Coco",
  "Embalagem Dallato Chocolate",
  "Aroma de Limão",
  "Farofa",
  "B. de Amônio",
  "Farinha de Trigo Sc",
  "Sal",
  "Margarina M. Ouro",
  "Amido de Milho",
  "Gordura Hid.",
  "Tempero Cebola",
  "Tempero Mant.",
  "Tempero Alho",
  "Esponja",
  "Fermento",
  "Paulivita",
  "Açúcar"
].sort(); // já ordena alfabeticamente
