const ingredientes = [
  { nome: "Ácido Cítrico", unidade: "kg" },
  { nome: "Ajinomoto", unidade: "kg" },
  { nome: "Alho Natural", unidade: "kg" },
  { nome: "Amido de Milho", unidade: "kg" },
  { nome: "Aroma de Alho", unidade: "ml" },
  { nome: "Aroma de Baunilha", unidade: "ml" },
  { nome: "Aroma de Cebola", unidade: "ml" },
  { nome: "Aroma de Chocolate", unidade: "ml" },
  { nome: "Aroma de Coco", unidade: "ml" },
  { nome: "Aroma de Leite Condensado", unidade: "ml" },
  { nome: "Aroma de Limão", unidade: "ml" },
  { nome: "Aroma de Maisena", unidade: "ml" },
  { nome: "Aroma de Manteiga", unidade: "ml" },
  { nome: "Aroma de Milho", unidade: "ml" },
  { nome: "Aroma de Queijo Parmesão", unidade: "ml" },
  { nome: "Aroma Três Leites", unidade: "ml" },
  { nome: "Açúcar", unidade: "kg" },
  { nome: "Bicarbonato de Amônio", unidade: "kg" },
  { nome: "Bicarbonato de Sódio", unidade: "kg" },
  { nome: "Cacau em Pó", unidade: "kg" },
  { nome: "Caramelo", unidade: "kg" },
  { nome: "Cebola Natural", unidade: "kg" },
  { nome: "Chocolate em Pó", unidade: "kg" },
  { nome: "Enzimas", unidade: "kg" },
  { nome: "Farelo", unidade: "kg" },
  { nome: "Farinha de Trigo", unidade: "kg" },
  { nome: "Farofa", unidade: "kg" },
  { nome: "Fécula de Mandioca", unidade: "kg" },
  { nome: "Fermento", unidade: "g" },
  { nome: "Fubá de Milho", unidade: "kg" },
  { nome: "Gelatina de Milho", unidade: "kg" },
  { nome: "Gordura Hidrogenada", unidade: "kg" },
  { nome: "Gordura Líquida Vegetal", unidade: "kg" },
  { nome: "Lecitina de Soja", unidade: "kg" },
  { nome: "Manteiga", unidade: "kg" },
  { nome: "Margarina", unidade: "kg" },
  { nome: "Mel Caseiro", unidade: "kg" },
  { nome: "Metabissulfito", unidade: "kg" },
  { nome: "Milho Gelatinizado", unidade: "kg" },
  { nome: "Milho In Natura", unidade: "kg" },
  { nome: "Óleo de Soja", unidade: "ml" },
  { nome: "Óleo Pronto Cebola", unidade: "ml" },
  { nome: "Paulialfa", unidade: "kg" },
  { nome: "Paulitase", unidade: "kg" },
  { nome: "Paulivita", unidade: "kg" },
  { nome: "Pirofosfato", unidade: "kg" },
  { nome: "Sal", unidade: "kg" },
  { nome: "Soro de Leite", unidade: "kg" },
  { nome: "Tempero de Alho", unidade: "kg" },
  { nome: "Tempero de Cebola", unidade: "kg" },
  { nome: "Tempero de Manteiga", unidade: "kg" },
  { nome: "Unimelo", unidade: "kg" }
];
