const ingredientes = [
  { nome: "Ácido Cítrico" },
  { nome: "Açúcar Refinado" },
  { nome: "Açúcar" },
  { nome: "Ajinomoto" },
  { nome: "Alho Natural" },
  { nome: "Amido de Milho" },
  { nome: "Aroma de Baunilha" },
  { nome: "Aroma de Cebola" },
  { nome: "Aroma de Chocolate" },
  { nome: "Aroma de Leite Condensado" },
  { nome: "Aroma de Coco" },
  { nome: "Aroma de Três Leites" },
  { nome: "Aroma de Maisena" },
  { nome: "Aroma de Manteiga" },
  { nome: "Aroma de Maria" },
  { nome: "Aroma de Milho" },
  { nome: "Aroma de Alho" },
  { nome: "Caramelo" },
  { nome: "Aroma de Queijo Parmesão" },
  { nome: "Bicarbonato de Amônio" },
  { nome: "Bicarbonato de Sódio" },
  { nome: "Cacau em Pó" },
  { nome: "Cebola Natural Roxa" },
  { nome: "Caixa de Papelão" },
  { nome: "Saco para Embalagem" },
  { nome: "Chocolate em Pó" },
  { nome: "Embalagem Transparente Lisa" },
  { nome: "Embalagem Folhada Cebola" },
  { nome: "Embalagem Folhada Alho" },
  { nome: "Embalagem Folhada Manteiga" },
  { nome: "Milho In Natura" },
  { nome: "Farelo" },
  { nome: "Fubá de Milho" },
  { nome: "Embalagem Milho" },
  { nome: "Enzimas" },
  { nome: "Embalagem 8 Grãos" },
  { nome: "Embalagem Água e Sal" },
  { nome: "Embalagem Integral" },
  { nome: "Embalagem Rainha Maisena" },
  { nome: "Embalagem Rainha Leite" },
  { nome: "Embalagem Rainha Cracker" },
  { nome: "Embalagem Rainha Rosca Leite" },
  { nome: "Embalagem Rainha Rosca Chocolate" },
  { nome: "Embalagem Rainha Rosca Coco" },
  { nome: "Embalagem Rainha Manteiga" },
  { nome: "Embalagem Rainha Alho" },
  { nome: "Embalagem Rainha Cebola" },
  { nome: "Farinha de Trigo Fama Panificação" },
  { nome: "Farinha de Trigo Panete Comum" },
  { nome: "Farinha de Trigo Evita" },
  { nome: "Fécula de Mandioca" },
  { nome: "Fermento" },
  { nome: "Gordura Vegetal" },
  { nome: "Lecitina de Soja" },
  { nome: "Manteiga Itacolomir" },
  { nome: "Margarina Folhada" },
  { nome: "Margarina" },
  { nome: "Mel Caseiro" },
  { nome: "Metabissulfito" },
  { nome: "Óleo de Soja" },
  { nome: "Milho Gelatinizado" },
  { nome: "Gordura Líquida Vegetal" },
  { nome: "Paulialfa" },
  { nome: "Paulitase" },
  { nome: "Paulivita" },
  { nome: "Pirofosfato" },
  { nome: "Sal Micronizado" },
  { nome: "Sal Refinado" },
  { nome: "Soro de Leite" },
  { nome: "Unimelo" },
  { nome: "Etiquetas" },
  { nome: "Embalagem de Caixa para Folhada" },
  { nome: "Óleo Pronto Cebola" },
  { nome: "Filme Rezinite" },
  { nome: "Fita Sela Caixa" },
  { nome: "Gelatina de Milho" },
  { nome: "Embalagem Flocão" },
  { nome: "Embalagem Dallato Leite" },
  { nome: "Embalagem Dallato Coco" },
  { nome: "Embalagem Dallato Chocolate" },
  { nome: "Aroma de Limão" },
  { nome: "Farofa" },
  { nome: "Gordura Hidrogenada" },
  { nome: "Tempero Cebola" },
  { nome: "Cebola Natural" },
  { nome: "Tempero Manteiga" },
  { nome: "Tempero Alho" },
  { nome: "Esponja" }
];
